name: PHP CI

on: push

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.1', '8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Run tests lowest
      run: dependencies=lowest ./project_tests.sh

    - name: Run tests default
      run: dependencies=default ./project_tests.sh
